// Site ayarlarının tek kaynağı: varsayılan değerler (veritabanı boşken site bunlarla açılır)
// ve admin panelindeki "Site Ayarları" formu bu listeden üretilir.

export type SettingField = {
  key: string;
  label: string;
  type?: "text" | "textarea" | "image" | "number" | "checkbox" | "color";
  hint?: string;
  default: string;
  wide?: boolean;
};

export type SettingGroup = { title: string; description?: string; fields: SettingField[] };

export const settingGroups: SettingGroup[] = [
  {
    title: "🏷️ Marka ve genel bilgiler",
    fields: [
      { key: "site_name", label: "Site adı", default: "Orimini" },
      { key: "slogan", label: "Slogan (İngilizce üst yazı)", default: "Custom-made for little ones" },
      { key: "tagline", label: "Kısa tanım", default: "Kişiye özel nakışlı bebek ve çocuk kıyafetleri", wide: true },
      {
        key: "site_description",
        label: "Site açıklaması (Google'da görünen varsayılan açıklama)",
        type: "textarea",
        wide: true,
        default:
          "Orimini, Adana'da el emeğiyle hazırlanan kişiye özel nakışlı salopet takımlar, kız çocuk elbiseleri ve yenidoğan setleri sunar. 0-3 aydan 10 yaşa kadar beden seçenekleri, WhatsApp ile kolay sipariş.",
      },
      {
        key: "keywords",
        label: "Anahtar kelimeler (virgülle ayırın)",
        type: "textarea",
        wide: true,
        default:
          "kişiye özel bebek kıyafeti, isim nakışlı salopet takım, kısa salopet takım, uzun salopet takım, kız çocuk elbise, doğum günü kıyafeti, bebek papyonlu takım, Adana bebek giyim",
      },
      {
        key: "site_url",
        label: "Site adresi (alan adı)",
        hint: "Boş bırakılırsa https://orimini.vercel.app kullanılır. Örn: https://www.orimini.com",
        default: "",
      },
      { key: "theme_color", label: "Tarayıcı tema rengi", type: "color", default: "#F7F1E8" },
    ],
  },
  {
    title: "🖼️ Logo ve görseller",
    fields: [
      { key: "logo_url", label: "Header logosu", type: "image", default: "/images/orimini-logo-yazi.webp" },
      { key: "footer_logo_url", label: "Footer logosu (boşsa header logosu)", type: "image", default: "" },
      {
        key: "schema_logo_url",
        label: "Kare logo / monogram (Google için)",
        type: "image",
        default: "/images/orimini-monogram.png",
      },
      { key: "favicon_url", label: "Favicon (boşsa varsayılan ikon)", type: "image", default: "" },
      {
        key: "og_image",
        label: "Paylaşım görseli (WhatsApp, Facebook önizlemesi)",
        type: "image",
        default: "",
        hint: "Boşsa varsayılan Orimini paylaşım görseli kullanılır.",
      },
    ],
  },
  {
    title: "📞 İletişim bilgileri",
    fields: [
      { key: "phone_display", label: "Telefon (görünen)", default: "0506 273 59 29" },
      { key: "phone_e164", label: "Telefon (arama linki, +90...)", default: "+905062735929" },
      { key: "whatsapp_number", label: "WhatsApp numarası (90 ile başlayan)", default: "905062735929" },
      { key: "email", label: "E-posta", default: "" },
      { key: "city", label: "Şehir", default: "Adana" },
      { key: "region", label: "Bölge / il", default: "Adana" },
      { key: "address", label: "Adres", default: "Adana, Türkiye", wide: true },
      { key: "working_hours", label: "Çalışma saatleri", default: "Pazartesi - Cumartesi, 09:00 - 19:00" },
      { key: "instagram", label: "Instagram adresi (tam link)", default: "" },
      { key: "facebook", label: "Facebook adresi (tam link)", default: "" },
      { key: "tiktok", label: "TikTok adresi (tam link)", default: "" },
      {
        key: "google_maps_embed",
        label: "Google Maps embed linki (iletişim sayfasında harita)",
        type: "textarea",
        wide: true,
        default: "",
        hint: "Google Maps > Paylaş > Harita yerleştir kısmındaki src=\"...\" adresini yapıştırın.",
      },
    ],
  },
  {
    title: "📢 Üst duyuru bandı",
    fields: [
      { key: "announcement_active", label: "Duyuru bandı açık", type: "checkbox", default: "true" },
      {
        key: "announcement_text",
        label: "Duyuru yazısı",
        wide: true,
        default: "Adana'dan tüm Türkiye'ye kargo · İsim nakışı ücretsiz",
      },
      {
        key: "announcement_show_whatsapp",
        label: "Duyurunun sonunda WhatsApp numarası görünsün",
        type: "checkbox",
        default: "true",
      },
    ],
  },
  {
    title: "🛍️ Sipariş, kargo ve ürün sayfası",
    description: "Metinlerde {kargo_limit}, {sehir}, {telefon}, {site_adi} gibi kısa kodlar kullanabilirsiniz.",
    fields: [
      { key: "free_shipping_limit", label: "Ücretsiz kargo limiti (TL)", type: "number", default: "2500" },
      {
        key: "price_note",
        label: "Fiyatın altındaki not",
        type: "textarea",
        wide: true,
        default: "{kargo_limit} ve üzeri siparişlerde kargo ücretsiz. Ödeme ve teslimat WhatsApp üzerinden netleştirilir.",
      },
      {
        key: "product_trust_items",
        label: "Ürün sayfası güven maddeleri (her satır: ikon | yazı)",
        type: "textarea",
        wide: true,
        hint: "İkonlar: nakis, kalp, kargo, kalkan, whatsapp, cetvel",
        default: "nakis | Ücretsiz isim nakışı\nkalp | El emeği dikim\nkargo | Türkiye geneli kargo\nkalkan | Nakış onayı sonrası üretim",
      },
      {
        key: "product_shipping_text",
        label: "Ürün sayfası \"Kargo, teslimat ve iade\" metni (HTML)",
        type: "textarea",
        wide: true,
        default:
          '<p>Siparişler nakış onayından sonra hazırlanır ve genellikle 3-7 iş günü içinde kargoya verilir. {sehir} içi elden teslim için bizimle iletişime geçebilirsiniz.</p><p>Kişiye özel nakış işlenen ürünlerde, üretim hatası dışında iade ve değişim yapılamaz. Ayrıntılar için <a href="/kargo-ve-iade">Kargo ve İade</a> sayfasına bakın.</p>',
      },
      { key: "personalization_label", label: "Varsayılan nakış alanı başlığı", default: "Nakış yapılacak isim / tarih" },
      {
        key: "personalization_placeholder",
        label: "Varsayılan nakış örneği",
        default: "Örn: Muhammed Eren - 28.08.2025",
      },
      {
        key: "personalization_note",
        label: "Varsayılan nakış notu",
        type: "textarea",
        wide: true,
        default:
          "İsim ve tarih nakışı ücretsizdir. Yazım kontrolü için siparişten sonra WhatsApp üzerinden teyit alınır.",
      },
      {
        key: "order_note_placeholder",
        label: "Sipariş notu örneği",
        default: "Örn: Teslim tarihi, renk tercihi, özel istekler",
      },
      {
        key: "cart_whatsapp_hint",
        label: "Sepet sayfasındaki WhatsApp açıklaması",
        type: "textarea",
        wide: true,
        default:
          "Mesajınız {telefon} numaralı WhatsApp hattımıza hazır olarak açılır. Ödeme ve teslimat bilgilerini oradan netleştiriyoruz.",
      },
      {
        key: "reviews_note",
        label: "Yorum formu altındaki not",
        type: "textarea",
        wide: true,
        default: "Yorumunuz bize ulaşır, onaylandıktan sonra burada yayınlanır.",
      },
    ],
  },
  {
    title: "📌 Footer",
    fields: [
      {
        key: "footer_about_text",
        label: "Footer tanıtım yazısı",
        type: "textarea",
        wide: true,
        default: "Kişiye özel nakışlı bebek ve çocuk kıyafetleri. Her parça, küçükler için sevgiyle ve özenle hazırlanır.",
      },
      { key: "footer_whatsapp_button", label: "Footer WhatsApp butonu yazısı", default: "WhatsApp'tan yazın" },
      {
        key: "footer_bottom_text",
        label: "En alt yazı (© yıl ve site adından sonra)",
        wide: true,
        default: "{sehir} · Siparişler WhatsApp üzerinden alınır.",
      },
    ],
  },
  {
    title: "🍪 Çerez / KVKK bildirimi",
    fields: [
      { key: "consent_active", label: "Bildirim açık", type: "checkbox", default: "true" },
      {
        key: "consent_text",
        label: "Bildirim yazısı",
        type: "textarea",
        wide: true,
        hint: "{kvkk} ve {cerez} kısa kodları tıklanabilir linke dönüşür.",
        default:
          "Sitemizde yalnızca sepet ve favorilerinizi hatırlamak için tarayıcı depolaması kullanıyoruz. Kişisel verileriniz {kvkk} ve {cerez} kapsamında korunur.",
      },
    ],
  },
  {
    title: "💬 WhatsApp mesaj şablonları",
    description: "Butonlara basınca WhatsApp'ta hazır açılan mesajlar. {urun} ve {kod} ürün adı/kodu ile değişir.",
    fields: [
      { key: "wa_question", label: "Genel soru mesajı", type: "textarea", wide: true, default: "Merhaba {site_adi}, ürünleriniz hakkında bilgi almak istiyorum." },
      { key: "wa_product_question", label: "Ürün hakkında soru mesajı", type: "textarea", wide: true, default: 'Merhaba {site_adi}, "{urun}" ({kod}) hakkında bilgi almak istiyorum.' },
      { key: "wa_single_order", label: "Tek ürün sipariş mesajı (başlangıç)", wide: true, default: "Merhaba {site_adi}, bu ürünü sipariş vermek istiyorum:" },
      { key: "wa_cart_order", label: "Sepet sipariş mesajı (başlangıç)", wide: true, default: "Merhaba {site_adi}, aşağıdaki ürünleri sipariş vermek istiyorum:" },
      { key: "wa_review", label: "Yorum mesajı (veritabanı yoksa)", wide: true, default: "Merhaba {site_adi}, ürün yorumu göndermek istiyorum:" },
      { key: "wa_lbl_product", label: "Mesaj satırı: Ürün", default: "Ürün" },
      { key: "wa_lbl_code", label: "Mesaj satırı: Ürün kodu", default: "Ürün kodu" },
      { key: "wa_lbl_category", label: "Mesaj satırı: Kategori", default: "Kategori" },
      { key: "wa_lbl_size", label: "Mesaj satırı: Yaş / Beden", default: "Yaş / Beden" },
      { key: "wa_lbl_qty", label: "Mesaj satırı: Adet", default: "Adet" },
      { key: "wa_lbl_embroidery", label: "Mesaj satırı: Nakış (isim/tarih)", default: "Nakış (isim/tarih)" },
      { key: "wa_lbl_note", label: "Mesaj satırı: Not", default: "Not" },
      { key: "wa_lbl_price", label: "Mesaj satırı: Fiyat", default: "Fiyat" },
      { key: "wa_lbl_link", label: "Mesaj satırı: Link", default: "Link" },
      { key: "wa_lbl_total", label: "Mesaj satırı: Toplam", default: "Toplam" },
      { key: "wa_lbl_name", label: "Mesaj satırı: Ad Soyad", default: "Ad Soyad" },
      { key: "wa_lbl_city", label: "Mesaj satırı: İl / İlçe", default: "İl / İlçe" },
      { key: "wa_lbl_order_note", label: "Mesaj satırı: Sipariş notu", default: "Sipariş notu" },
      { key: "wa_lbl_rating", label: "Mesaj satırı: Puan", default: "Puan" },
      { key: "wa_lbl_comment", label: "Mesaj satırı: Yorum", default: "Yorum" },
    ],
  },
  {
    title: "📝 Site metinleri: genel, header ve footer",
    fields: [
      { key: "txt_search_placeholder", label: "Arama kutusu yazısı", default: "Ürün ara… (ör. salopet, elbise)" },
      { key: "txt_search_empty", label: "Hızlı aramada sonuç yok ({q} = aranan)", default: '"{q}" için ürün bulunamadı.' },
      { key: "txt_search_all", label: "Hızlı arama: tüm sonuçlar linki", default: "Tüm sonuçları gör" },
      { key: "txt_breadcrumb_home", label: "Sayfa yolunda anasayfa", default: "Anasayfa" },
      { key: "txt_footer_categories", label: "Footer: kategoriler başlığı", default: "Kategoriler" },
      { key: "txt_footer_all_products", label: "Footer: tüm ürünler linki", default: "Tüm Ürünler" },
      { key: "txt_footer_corporate", label: "Footer: kurumsal başlığı", default: "Kurumsal" },
      { key: "txt_footer_contact", label: "Footer: iletişim başlığı", default: "İletişim" },
      { key: "txt_category_card_link", label: "Anasayfa kategori kartı linki", default: "İncele →" },
      { key: "txt_sale_badge", label: "Kırmızı görünen etiket adı", hint: "Üründe bu etiket varsa kırmızı (indirim) renginde görünür.", default: "İndirim" },
      { key: "txt_favorite", label: "Beğen butonu", default: "Beğen" },
      { key: "txt_favorited", label: "Beğenildi butonu", default: "Beğenildi" },
      { key: "txt_consent_accept", label: "Çerez bildirimi butonu", default: "Anladım" },
      { key: "txt_last_updated", label: "Sözleşmelerde \"son güncelleme\" yazısı", default: "Son güncelleme" },
      { key: "txt_404_title", label: "404 sayfası başlığı", default: "Aradığınız sayfa bulunamadı" },
      { key: "txt_404_text", label: "404 sayfası yazısı", wide: true, default: "Sayfa taşınmış ya da kaldırılmış olabilir. Koleksiyonumuza göz atabilirsiniz." },
      { key: "txt_404_button", label: "404 sayfası butonu", default: "Ürünlere git" },
    ],
  },
  {
    title: "📝 Site metinleri: ürün listeleme ve arama",
    fields: [
      { key: "txt_filter_category", label: "Filtre: kategori", default: "Kategori" },
      { key: "txt_filter_size", label: "Filtre: yaş / beden", default: "Yaş / Beden" },
      { key: "txt_filter_all", label: "Filtre: tümü", default: "Tümü" },
      { key: "txt_sort", label: "Sıralama başlığı", default: "Sırala" },
      { key: "txt_sort_recommended", label: "Sıralama: önerilen", default: "Önerilen" },
      { key: "txt_sort_price_asc", label: "Sıralama: artan fiyat", default: "Fiyat: Düşükten yükseğe" },
      { key: "txt_sort_price_desc", label: "Sıralama: azalan fiyat", default: "Fiyat: Yüksekten düşüğe" },
      { key: "txt_products_count", label: "Ürün sayısı ({n} = adet)", default: "{n} ürün" },
      { key: "txt_listing_empty", label: "Filtre sonucu boş", wide: true, default: "Bu filtrelere uygun ürün bulunamadı. Farklı bir beden seçmeyi deneyin." },
      { key: "txt_search_title", label: "Arama sayfası başlığı", default: "Ürün ara" },
      { key: "txt_search_results_title", label: "Arama sonuç başlığı ({q} = aranan)", default: '"{q}" için sonuçlar' },
      { key: "txt_search_found", label: "Bulunan ürün sayısı ({n} = adet)", default: "{n} ürün bulundu." },
      { key: "txt_search_none", label: "Arama sonucu yok", wide: true, default: "Aradığınız ürünü bulamadık. Kategorilere göz atabilirsiniz:" },
    ],
  },
  {
    title: "📝 Site metinleri: ürün sayfası",
    fields: [
      { key: "txt_product_code", label: "Ürün kodu etiketi", default: "Ürün kodu" },
      { key: "txt_color", label: "Renk etiketi", default: "Renk" },
      { key: "txt_size", label: "Beden etiketi", default: "Beden" },
      { key: "txt_no_reviews_short", label: "Yorum yokken yıldızların yanı", default: "Henüz yorum yok · İlk yorumu yazın" },
      { key: "txt_reviews_suffix", label: "Yorum sayısı eki", default: "yorum" },
      { key: "txt_gallery_hint", label: "Galeri ipucu", wide: true, default: "Yakınlaştırmak için üzerine gelin, büyütmek için tıklayın" },
      { key: "txt_size_label", label: "Beden seçimi başlığı", default: "Yaş / Beden" },
      { key: "txt_size_guide_link", label: "Beden rehberi linki", default: "Beden rehberi" },
      { key: "txt_size_required", label: "Beden seçilmedi uyarısı", default: "Lütfen yaş / beden seçin." },
      { key: "txt_order_note_label", label: "Sipariş notu başlığı", default: "Sipariş notu (isteğe bağlı)" },
      { key: "txt_add_to_cart", label: "Sepete ekle butonu", default: "Sepete ekle" },
      { key: "txt_order_whatsapp", label: "WhatsApp sipariş butonu", default: "WhatsApp ile sipariş ver" },
      { key: "txt_added_to_cart", label: "Sepete eklendi mesajı", default: "Ürün sepete eklendi." },
      { key: "txt_go_to_cart", label: "Sepete git linki", default: "Sepete git" },
      { key: "txt_added_to_cart_suffix", label: "Sepete eklendi mesajı devamı", wide: true, default: "ve tüm ürünleri tek mesajla gönder." },
      { key: "txt_ask_product", label: "Ürün hakkında soru linki", default: "Bu ürün hakkında soru sor" },
      { key: "txt_tab_description", label: "Sekme: ürün açıklaması", default: "Ürün açıklaması" },
      { key: "txt_tab_set", label: "Sekme: set içeriği", default: "Set içeriği" },
      { key: "txt_tab_fabric", label: "Sekme: kumaş ve bakım", default: "Kumaş ve bakım" },
      { key: "txt_fabric", label: "Kumaş etiketi", default: "Kumaş" },
      { key: "txt_tab_shipping", label: "Sekme: kargo", default: "Kargo, teslimat ve iade" },
      { key: "txt_related", label: "Benzer ürünler başlığı", default: "Bunları da beğenebilirsiniz" },
    ],
  },
  {
    title: "📝 Site metinleri: sözleşme onayı ve yorumlar",
    description: "Onay cümlesinde {on_bilgi}, {mesafeli} ve {kvkk} tıklanabilir sözleşme linkine dönüşür.",
    fields: [
      { key: "txt_consent_sentence", label: "Sipariş onay cümlesi", type: "textarea", wide: true, default: "{on_bilgi}'nu ve {mesafeli}'ni okudum, onaylıyorum. {kvkk}'ni okudum." },
      { key: "txt_consent_error", label: "Onay verilmedi uyarısı", default: "Siparişe devam etmek için sözleşmeyi onaylayın." },
      { key: "txt_loading", label: "Sözleşme penceresi: yükleniyor", default: "Yükleniyor…" },
      { key: "txt_modal_error", label: "Sözleşme penceresi: yüklenemedi", default: "Metin yüklenemedi." },
      { key: "txt_modal_open_page", label: "Sözleşme penceresi: sayfayı aç linki", default: "Sayfayı açın." },
      { key: "txt_modal_close", label: "Sözleşme penceresi kapat butonu", default: "Okudum, kapat" },
      { key: "txt_reviews_title", label: "Yorumlar başlığı", default: "Ürün yorumları" },
      { key: "txt_reviews_count", label: "Değerlendirme sayısı eki", default: "değerlendirme" },
      { key: "txt_reviews_empty", label: "Yorum yok yazısı", wide: true, default: "Bu ürün için henüz yorum yok. İlk yorumu siz yazın!" },
      { key: "txt_review_form_title", label: "Yorum formu başlığı", default: "Yorum yazın" },
      { key: "txt_review_rating", label: "Puan etiketi", default: "Puanınız" },
      { key: "txt_review_rating_labels", label: "Yıldız açıklamaları (1'den 5'e, | ile ayırın)", wide: true, default: "Hiç beğenmedim | Beğenmedim | Fena değil | Beğendim | Çok beğendim" },
      { key: "txt_review_name", label: "Ad etiketi", default: "Adınız" },
      { key: "txt_review_city", label: "Şehir etiketi", default: "Şehir (isteğe bağlı)" },
      { key: "txt_review_comment", label: "Yorum etiketi", default: "Yorumunuz" },
      { key: "txt_review_submit", label: "Gönder butonu", default: "Yorumu gönder" },
      { key: "txt_review_sending", label: "Gönderiliyor yazısı", default: "Gönderiliyor…" },
      { key: "txt_review_error_send", label: "Gönderilemedi uyarısı", wide: true, default: "Yorum gönderilemedi, lütfen WhatsApp ile iletin." },
      { key: "txt_review_success", label: "Gönderildi mesajı", wide: true, default: "Teşekkürler! Yorumunuz bize ulaştı, onaylandıktan sonra burada yayınlanacak." },
      { key: "txt_review_error_rating", label: "Puan seçilmedi uyarısı", default: "Lütfen yıldız seçerek puan verin." },
      { key: "txt_review_error_text", label: "Ad/yorum eksik uyarısı", default: "Lütfen adınızı ve yorumunuzu yazın." },
    ],
  },
  {
    title: "📝 Site metinleri: sepet, favoriler, iletişim, beden rehberi",
    fields: [
      { key: "txt_cart_empty_title", label: "Sepet boş başlığı", default: "Sepetiniz boş" },
      { key: "txt_cart_empty_text", label: "Sepet boş yazısı", wide: true, default: "Beğendiğiniz ürünleri sepete ekleyip hepsini tek mesajla sipariş verebilirsiniz." },
      { key: "txt_cart_empty_button", label: "Sepet boş butonu", default: "Alışverişe başla" },
      { key: "txt_cart_size", label: "Sepet: beden etiketi", default: "Yaş / Beden" },
      { key: "txt_cart_embroidery", label: "Sepet: nakış etiketi", default: "Nakış" },
      { key: "txt_cart_per_item", label: "Sepet: adet fiyatı eki", default: "/ adet" },
      { key: "txt_cart_remove", label: "Sepet: kaldır", default: "Kaldır" },
      { key: "txt_cart_total", label: "Sepet: toplam", default: "Toplam" },
      { key: "txt_cart_free_shipping", label: "Kargo ücretsiz yazısı", default: "Kargo ücretsiz." },
      { key: "txt_cart_shipping_left", label: "Kargo için kalan ({kalan} = tutar)", wide: true, default: "{kalan} daha ekleyin, kargo ücretsiz olsun." },
      { key: "txt_cart_name", label: "Sepet: ad soyad etiketi", default: "Ad Soyad" },
      { key: "txt_cart_city", label: "Sepet: il/ilçe etiketi", default: "İl / İlçe" },
      { key: "txt_cart_city_placeholder", label: "Sepet: il/ilçe örneği", default: "Örn: Adana / Çukurova" },
      { key: "txt_cart_note", label: "Sepet: sipariş notu etiketi", default: "Sipariş notu" },
      { key: "txt_fav_empty_title", label: "Favori yok başlığı", default: "Henüz favori ürününüz yok" },
      { key: "txt_fav_empty_text", label: "Favori yok yazısı", wide: true, default: "Ürünlerin üzerindeki kalbe dokunarak beğendiklerinizi buraya ekleyebilirsiniz." },
      { key: "txt_fav_empty_button", label: "Favori yok butonu", default: "Ürünlere göz at" },
      { key: "txt_contact_whatsapp", label: "İletişim kartı: WhatsApp", default: "WhatsApp" },
      { key: "txt_contact_phone", label: "İletişim kartı: telefon", default: "Telefon" },
      { key: "txt_contact_email", label: "İletişim kartı: e-posta", default: "E-posta" },
      { key: "txt_contact_hours", label: "İletişim kartı: çalışma saatleri", default: "Çalışma saatleri" },
      { key: "txt_size_col", label: "Beden tablosu: beden sütunu", default: "Yaş / Beden" },
      { key: "txt_height_col", label: "Beden tablosu: boy sütunu", default: "Boy" },
      { key: "txt_weight_col", label: "Beden tablosu: kilo sütunu", default: "Kilo" },
    ],
  },
  {
    title: "⚖️ Satıcı bilgileri (sözleşme ve KVKK metinlerinde kullanılır)",
    fields: [
      { key: "legal_title", label: "Resmi unvan", default: "Orimini" },
      { key: "legal_address", label: "Açık adres", default: "Adana, Türkiye", wide: true },
      { key: "legal_tax_info", label: "Vergi dairesi / no", default: "" },
      { key: "legal_email", label: "Yasal e-posta", default: "" },
      { key: "legal_kep", label: "KEP adresi", default: "" },
      { key: "legal_updated_at", label: "Sözleşmelerin son güncelleme tarihi", default: "23.09.2026" },
    ],
  },
  {
    title: "🔍 Arama motoru doğrulama kodları",
    description: "Sadece content değerini girin (meta etiketinin tamamını değil).",
    fields: [
      { key: "google_verification", label: "Google Search Console", default: "" },
      { key: "yandex_verification", label: "Yandex", default: "" },
      { key: "bing_verification", label: "Bing (msvalidate.01)", default: "" },
    ],
  },
];

export const settingDefaults: Record<string, string> = Object.fromEntries(
  settingGroups.flatMap((g) => g.fields.map((f) => [f.key, f.default])),
);
